# Generated by Django 4.2 on 2024-09-09 11:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "price",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                (
                    "order_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sneakers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_sneakers",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Sneakers Color",
                    ),
                ),
                (
                    "assignment_sneakers",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Assignment Sneakers",
                    ),
                ),
                (
                    "brand_sneakers",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Sneakers Brand",
                    ),
                ),
                (
                    "price_sneakers",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Sneakers Price",
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
                (
                    "image_sneakers",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/sneakers/"
                    ),
                ),
                (
                    "quantity_sneakers",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Sneakers Quantity"
                    ),
                ),
                (
                    "description_sneakers",
                    models.TextField(
                        default="A description will be coming soon",
                        verbose_name="Sneakers Description",
                    ),
                ),
                (
                    "stock_keeping_unit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="stock_keeping_unit",
                    ),
                ),
                (
                    "order_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sneakers",
                        to="sneakers_shop.orderdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SneakersCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_sneakers",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SneakersSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="sneakers_size"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sneakers_shop.sneakers",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SneakersToSizes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sneakers_shop.sneakerssize",
                    ),
                ),
                (
                    "sneakers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sneakers_shop.sneakers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sneakers_shop.orders",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_detail",
                to="sneakers_shop.orders",
            ),
        ),
        migrations.CreateModel(
            name="Carts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_cart", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total_price",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("cart_date", models.DateField(blank=True, null=True)),
                (
                    "sneakers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="sneakers_shop.sneakers",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
