# Generated by Django 4.2 on 2024-09-09 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sneakers_shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SneakersToCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sneakers_shop.sneakerscategories",
                    ),
                ),
                (
                    "sneakers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sneakers_shop.sneakers",
                    ),
                ),
            ],
        ),
    ]
