# Generated by Django 4.2 on 2024-05-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sneakers_shop", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
