# Generated by Django 4.2 on 2024-09-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sneakers_shop", "0002_sneakerstocategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sneakerstosizes",
            name="sneakers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size_relations",
                to="sneakers_shop.sneakers",
            ),
        ),
    ]
