# Generated by Django 4.2 on 2024-05-12 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sneakers_shop", "0003_orders_order_date_carts"),
    ]

    operations = [
        migrations.AddField(
            model_name="carts",
            name="cart_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carts",
            name="count_cart",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carts",
            name="total_price",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="price",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="quantity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="order_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="amount",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="sneakers",
            name="brand_sneakers",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="sneakers",
            name="color_sneakers",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="sneakers",
            name="image_sneakers",
            field=models.ImageField(blank=True, null=True, upload_to="media/sneakers/"),
        ),
        migrations.AddField(
            model_name="sneakers",
            name="model_sneakers",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="sneakers",
            name="price_sneakers",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="sneakers",
            name="size_sneakers",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sneakerscategories",
            name="category_sneakers",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
