# Generated by Django 4.2 on 2024-09-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sneakers_shop", "0003_alter_sneakerstosizes_sneakers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sneakerstocategories",
            name="sneakers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_relations",
                to="sneakers_shop.sneakers",
            ),
        ),
    ]
