# Generated by Django 4.2 on 2024-05-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "sneakers_shop",
            "0004_carts_cart_date_carts_count_cart_carts_total_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sneakers",
            name="order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sneakers",
                to="sneakers_shop.orderdetail",
            ),
        ),
    ]
