version: '3'
#docker run --rm -it --name shop_cont -p 8010:8000 image_shop ./commands/start_server_dev.sh
services:
  backend:
    build: ./
    container_name: shop_cont
    working_dir: /shop
    ports:
      - "8010:8000"
    command:
      - ./commands/start_server_dev.sh
    volumes:
      - ./src:/shop/src
      - ./commands:/shop/commands/
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:13.7
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pg_data: { }



